/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cd0ecf12-56dc-4442-a6cb-c4d40a9b3259",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_smuCRb4xA",
    "aws_user_pools_web_client_id": "53encqf79f756i301g8kg34d7p",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://cymjegjsvfbfrje2oqcb4zrrfq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-isg7xn7iazh3poqo6cneizoprq",
    "aws_user_files_s3_bucket": "amplifyapp83a7166629c04363b3f9499c4c1a3bbc160906-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
